version: "3.1"
services:
  db:
    image: mysql
    container_name: helpdesk-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: helpdesk_db
    ports:
      - "3306:3306"
    volumes:
      - helpdesk_data:/var/lib/mysql

volumes:
  helpdesk_data: